const papers = [
  {
    "title": "Spontaneous Giving and Calculated Greed in Language Models",
    "authors": "<span class=\"author-highlight\">Yuxuan Li</span>, Hirokazu Shirado",
    "venue": "EMNLP 2025 Main | The 2025 Conference on Empirical Methods in Natural Language Processing",
    "venue_short": "EMNLP 2025 Main",
    "visibility": "both",
    "highlight": "Oral Presentation \uff5c Extensive Media Coverage",
    "image": "images/2025-02-24-EMNLP2025.png",
    "excerpt": "Reasoning models are greedier. We find that reasoning models consistently exhibit lower cooperation and reduced norm-enforced punishment, mirroring human tendencies of \"spontaneous giving and calculated greed\".",
    "paper": "https://aclanthology.org/2025.emnlp-main.267/",
    "video": "https://drive.google.com/file/d/1SKc1gaOFrz0Pjq4-x63sVU934snLKiII/view?usp=sharing",
    "media": [
      { "title": "Is AI Becoming Selfish?", "outlet": "Carnegie Mellon University", "url": "https://www.cs.cmu.edu/news/2025/selfish-ai" },
      { "title": "Smarter AI Models Show Selfish Behavior in Study", "outlet": "The Chosun Ilbo", "url": "https://www.chosun.com/english/national-en/2025/11/08/ADPWF3BV4JFI5C3PBY3NVTRL2Q/" },
      { "title": "AI showing signs of selfishness, researchers warn of troubling trend", "outlet": "The News International", "url": "https://www.thenews.com.pk/latest/1355063-ai-showing-signs-of-selfishness-researchers-warn-of-troubling-trend" },
      { "title": "When AI LLMs think more, groups suffer, CMU study finds", "outlet": "Geneva Internet Platform (Dig.watch)", "url": "https://dig.watch/updates/when-ai-llms-think-more-groups-suffer-cmu-study-finds" },
      { "title": "Yapay zeka ak\u0131l y\u00fcr\u00fctme kapasitesi artt\u0131k\u00e7a bencille\u015fiyor", "outlet": "NTV", "url": "https://www.ntv.com.tr/teknoloji/yapay-zeka-akil-yurutme-kapasitesi-arttikca-bencillesiyor,spd3iOrTGEqppNV_AL1siA" },
      { "title": "Your friendly neighbourhood AI just got smart and surprisingly selfish", "outlet": "Digital Trends", "url": "https://www.digitaltrends.com/computing/your-friendly-neighbourhood-ai-just-got-smart-and-surprisingly-selfish/" },
      { "outlet": "TribLIVE", "url": "https://triblive.com/local/cmu-researchers-find-selfish-traits-in-cutting-edge-ai/" },
      { "outlet": "TechNews (via LINE Today)", "url": "https://today.line.me/tw/v3/article/MLnDLMw" },
      { "outlet": "Yahoo News", "url": "https://www.yahoo.com/news/articles/friendly-neighbourhood-ai-just-got-043255774.html" },
      { "outlet": "Levante-EMV", "url": "https://www.levante-emv.com/tendencias21/2025/11/06/inteligencia-artificial-desarrollada-tiende-egoismo-123411677.html" },
      { "outlet": "ABC Gazetesi", "url": "https://abcgazetesi.com.tr/yapay-zekanin-zekilestikce-bencillestigi-ortaya-cikti-849487" },
      { "outlet": "GeneOnline", "url": "https://www.geneonline.com/carnegie-mellon-study-finds-advanced-ai-systems-tend-to-prioritize-self-interest-over-collaboration/" },
      { "outlet": "Digital Information World", "url": "https://www.digitalinformationworld.com/2025/10/carnegie-mellon-study-finds-advanced-ai.html" },
      { "outlet": "Asianet Newsable", "url": "https://newsable.asianetnews.com/international/science/ai-may-turn-self-centered-as-it-becomes-more-intelligent-articleshow-9g8y1om" },
      { "outlet": "DevDiscourse", "url": "https://www.devdiscourse.com/article/technology/3680185-advanced-ai-is-becoming-more-selfish-as-it-learns-to-reason" },
      { "outlet": "Euro Security", "url": "https://euro-security.de/en/artificial-intelligence-is-becoming-increasingly-selfish/" },
      { "outlet": "PsyPost", "url": "https://www.psypost.org/smarter-ai-models-show-more-selfish-behavior/" },
      { "outlet": "Mundiario", "url": "https://www.mundiario.com/articulo/tecnologia-ciencia/puede-inteligencia-artificial-volverse-egoista-probablemente-medida-que-evoluciona/20251103060709361661.html" },
      { "outlet": "AZoAI", "url": "https://www.azoai.com/news/20251102/Smarter-AI-Selfish-AI-Carnegie-Mellon-Study-Reveals-Downside-Of-Machine-Reasoning.aspx" },
      { "outlet": "Revista Perspectiva", "url": "https://revistaperspectiva.mx/puede-la-inteligencia-artificial-volverse-egoista-probablemente-si-a-medida-que-evoluciona/" },
      { "outlet": "cnBeta", "url": "https://m.cnbeta.com.tw/view/1533946.htm" },
      { "outlet": "Referans T\u00fcrk", "url": "https://www.referansturk.com.tr/haber/26735824/yapay-zeka-akil-yurutme-kapasitesi-arttikca-bencillesiyor" },
      { "outlet": "Knowridge", "url": "https://knowridge.com/2025/11/the-smarter-ai-gets-the-more-selfish-it-becomes-study-warns/" },
      { "outlet": "Bioengineer.org", "url": "https://bioengineer.org/is-artificial-intelligence-developing-self-interested-behavior/" },
      { "outlet": "Scienmag", "url": "https://scienmag.com/is-artificial-intelligence-developing-self-interested-behavior/" },
      { "outlet": "InnoLabs", "url": "https://www.innolabs.ro/ai-lens/2025-10-31-as-ai-evolves-the-double-edged-sword-of-intelligence-and-selfishness" },
      { "outlet": "Xenospectrum", "url": "https://xenospectrum.com/ai-becomes-more-selfish-as-it-grows-smarter/" },
      { "outlet": "Kosmicki Glasnik", "url": "https://kosmickiglasnik.rs/naucnici-dokazali-vestacka-inteligencija-sve-sebicnija/" },
      { "outlet": "Rexmolon", "url": "https://www.rexmolon.es/rexmolon-producciones-noticias-de-generacion-de-contenidos-digitales/inteligencia-artificial-el-dilema-moral-de-los-modelos-de-lenguaje" },
      { "outlet": "Tunceli Emek", "url": "https://www.tunceliemek.com.tr/haber/26738633/ilginc-arastirma-yapay-zeka-zekilestikce-daha-bencil-oluyor" },
      { "outlet": "Cong Dong AI", "url": "https://congdongai.vn/threads/ai-cang-thong-minh-cang-co-the-tro-nen-ich-ky.1700/" },
      { "outlet": "SciTke", "url": "https://scitke.com/as-ai-develops-further-it-could-become-more-self-serving/" },
      { "outlet": "JDYX", "url": "https://www.jdyx.cc/news/show-5683.html" },
      { "outlet": "INF News", "url": "https://inf.news/en/tech/0c78ea87bdf4b93c8938fe736935531f.html" },
      { "outlet": "INF News", "url": "https://inf.news/en/science/8d1d38df68566d102e0f92e99e1e95a8.html" },
      { "outlet": "Haber Cephesi", "url": "https://habercephesi.com.tr/yapay-zeka-akillanirken-bencillesiyor/370766/" },
      { "outlet": "The Daily Horizon", "url": "https://thedailyhorizon.myshopify.com/blogs/technology/ai-dark-turn-cmu-study" },
      { "outlet": "Wisdom Superman", "url": "https://www.wisdomsuperman.com/en/ai-is-more-intelligent-but-also-more-selfish" },
      { "outlet": "E-G\u00fcndem", "url": "https://egundem.com/bilim-and-teknoloji/yapay-zekanin-zekilestikce-bencillestigi-kesfedildi-152c67ef" },
      { "outlet": "Kad\u0131n Elit", "url": "https://kadinelit.com.tr/yapay-zeka-akil-yurutme-kapasitesi-artarken-bencillesiyor/" },
      { "outlet": "AI Buzz", "url": "https://www.ai-buzz.com/study-ai-models-show-60-drop-in-cooperation-when-reasoning" },
      { "outlet": "Hi-Network", "url": "https://pt.hi-network.com/when-ai-llms-think-more-groups-suffer-cmu-study-finds.html" },
      { "outlet": "AI Search", "url": "https://ai-search.io/articles/smarter-ai-exhibits-selfish-behavior-hindering-cooperation" },
      { "outlet": "DeepTechBytes", "url": "https://deeptechbytes.com/ai-is-learning-to-be-selfish-study-warns/" },
      { "outlet": "The420", "url": "https://the420.in/carnegie-mellon-ai-reasoning-study-selfish-behaviour-social-impact/" }
    ],
    "cite": `@inproceedings{li2025spontaneous,
  title={Spontaneous giving and calculated greed in language models},
  author={Li, Yuxuan and Shirado, Hirokazu},
  booktitle={Proceedings of the 2025 Conference on Empirical Methods in Natural Language Processing},
  pages={5271--5286},
  year={2025}
}`
  },
  {
    "title": "Actions Speak Louder than Words: Agent Decisions Reveal Implicit Biases in Language Models",
    "authors": "<span class=\"author-highlight\">Yuxuan Li</span>, Hirokazu Shirado, Sauvik Das",
    "venue": "FAccT 2025 | ACM Conference on Fairness, Accountability, and Transparency",
    "venue_short": "FAccT 2025",
    "visibility": "both",
    "image": "images/2025-06-23-FAccT2025.png",
    "excerpt": "LLMs are increasingly implicitly biased. We find that when simulating human behavior (actions), more advanced models exhibit stronger sociodemographic biases, even though these biases appear reduced when measured explicitly through Q&A (words).",
    "paper": "https://dl.acm.org/doi/full/10.1145/3715275.3732212",
    "video": "https://drive.google.com/file/d/1Sun76E1Il89HOxQdwKBMgMSyBu7_zVXt/view?usp=sharing",
    "cite": `@inproceedings{li2025actions,
  title={Actions speak louder than words: Agent decisions reveal implicit biases in language models},
  author={Li, Yuxuan and Shirado, Hirokazu and Das, Sauvik},
  booktitle={Proceedings of the 2025 ACM Conference on Fairness, Accountability, and Transparency},
  pages={3303--3325},
  year={2025}
}`
  },
  {
    "title": "What Makes LLM Agent Simulations Useful for Policy Practice? An Iterative Design Study in Emergency Preparedness",
    "authors": "<span class=\"author-highlight\">Yuxuan Li</span>, Sauvik Das, Hirokazu Shirado",
    "venue": "Under review at TOCHI",
    "venue_short": "TOCHI (Under Review)",
    "visibility": "both",
    "image": "images/2025-09-26-CHI2026-submission-a.png",
    "excerpt": "LLM agent simulations can be genuinely useful for policy. We work closely with policymakers over 16 months to design and build a 13,000-agent simulation system that directly informed and improved policy at CMU.",
    "paper": "https://arxiv.org/abs/2509.21868",
    "cite": `@article{li2025makes,
  title={What Makes LLM Agent Simulations Useful for Policy? Insights From an Iterative Design Engagement in Emergency Preparedness},
  author={Li, Yuxuan and Das, Sauvik and Shirado, Hirokazu},
  journal={arXiv preprint arXiv:2509.21868},
  year={2025}
}`
  },
  {
    "title": "Systematic Failures in Collective Reasoning under Distributed Information in Multi-Agent LLMs",
    "authors": "<span class=\"author-highlight\">Yuxuan Li</span>, Aoi Naito, Hirokazu Shirado",
    "venue": "Under review at ICML 2026",
    "venue_short": "ICML 2026 (Under Review)",
    "visibility": "both",
    "image": "images/2025-09-25-ICLR2026-submission-a.png",
    "excerpt": "Multi-agent LLM systems fail at collective reasoning, much like human groups. We demonstrate this by formalizing the Hidden Profile paradigm from social psychology and constructing a scalable 65-task benchmark based on this formalization.",
    "paper": "https://arxiv.org/abs/2505.11556",
    "cite": `@article{li2025assessing,
  title={Assessing Collective Reasoning in Multi-Agent LLMs via Hidden Profile Tasks},
  author={Li, Yuxuan and Naito, Aoi and Shirado, Hirokazu},
  journal={arXiv preprint arXiv:2505.11556},
  year={2025}
}`
  },
  {
    "title": "WhatIf: Interactive Exploration of LLM-Powered Social Simulations for Policy Reasoning",
    "authors": "<span class=\"author-highlight\">Yuxuan Li</span>, Kyzyl Monteiro, Hirokazu Shirado, Sauvik Das",
    "venue": "Under review at UIST 2026",
    "venue_short": "UIST 2026 (Under Review)",
    "visibility": "both",
    "image": "images/UIST2026.png",
    "excerpt": "Interactive systems unlock the value of LLM simulations. We introduce WhatIf, a system that lets policymakers steer, inspect, and compare large-scale agent simulations in real time, turning them into shared reasoning environments that support iterative what-if exploration, collaborative deliberation, and multi-level interpretation of behavior from individual agents to crowd dynamics.",
    "paper": "https://drive.google.com/file/d/17Xng8ZNKNPlhlae99rhj7hjKg65VPXoK/view"
  },
  {
    "title": "How Well Can LLM Agents Simulate End-User Security and Privacy Attitudes and Behaviors?",
    "authors": "<span class=\"author-highlight\">Yuxuan Li*</span>, Leyang Li*, Hao-Ping (Hank) Lee, Sauvik Das",
    "venue": "Under review at USENIX Security 2026",
    "venue_short": "USENIX Security 2026 (Under Review)",
    "visibility": "both",
    "image": "images/USENIX2026.png",
    "excerpt": "LLM agents are only moderately reliable proxies for user security and privacy behavior, yet. Using a new benchmark grounded in human-subject studies, we find that simulations achieve limited alignment (\u224850\u201364/100), with no consistent gains from larger or more advanced models, and strong dependence on persona design and prompting\u2014especially theory-informed prompts, which improve behavioral realism but can distort stated attitudes.",
    "paper": "https://arxiv.org/abs/2602.18464",
    "cite": `@article{li2026well,
  title={How Well Can LLM Agents Simulate End-User Security and Privacy Attitudes and Behaviors?},
  author={Li, Yuxuan and Li, Leyang and Das, Sauvik and others},
  journal={arXiv preprint arXiv:2602.18464},
  year={2026}
}`
  },
  {
    "title": "A Human-Computer Collaborative Tool for Training a Single Large Language Model Agent into a Network through Few Examples",
    "authors": "Lihang Pan*, <span class=\"author-highlight\">Yuxuan Li*</span>, Chun Yu, Yuanchun Shi",
    "venue": "arXiv 2024",
    "venue_short": "arXiv 2024",
    "visibility": "all",
    "image": "images/2024-04-24-EasyLAN.png",
    "excerpt": "We make it easy for novices to build powerful multi-agent LLM systems (MAS). We introduce EasyLAN, a human\u2013AI collaborative system that helps users construct MAS using only a few examples.",
    "paper": "https://arxiv.org/abs/2404.15974",
    "cite": `@article{pan2024human,
  title={A human-computer collaborative tool for training a single large language model agent into a network through few examples},
  author={Pan, Lihang and Li, Yuxuan and Yu, Chun and Shi, Yuanchun},
  journal={arXiv preprint arXiv:2404.15974},
  year={2024}
}`
  },
  {
    "title": "Say Your Reason: Extract Contextual Rules In Situ for Context-aware Service Recommendation",
    "authors": "<span class=\"author-highlight\">Yuxuan Li</span>, Jiahui Li, Lihang Pan, Chun Yu, Yuanchun Shi",
    "venue": "arXiv 2024",
    "venue_short": "arXiv 2024",
    "visibility": "all",
    "image": "images/2024-08-26-SayRea.png",
    "excerpt": "We make it easy to control service recommendations on users' mobile phones in situ. We introduce SayRea, an interactive system that helps extract contextual rules for personalized, context-aware service recommendations in mobile scenarios using LLMs.",
    "paper": "https://arxiv.org/abs/2408.13977",
    "cite": `@article{li2024say,
  title={Say Your Reason: Extract Contextual Rules In Situ for Context-aware Service Recommendation},
  author={Li, Yuxuan and Li, Jiahui and Pan, Lihang and Yu, Chun and Shi, Yuanchun},
  journal={arXiv preprint arXiv:2408.13977},
  year={2024}
}`
  }
];
